name: Deployment

env:
  DOTNET_VERSION: '6'
  
on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: Set up .NET 
      uses: actions/setup-dotnet@v3
      with: 
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore Nuget packages
      run: dotnet restore

    - name: Build Project
      run: dotnet build --no-restore

    - name: Publish
      run: dotnet publish -c release --output ./release
    
    # - name: 💥 Deploy
    #   uses: Samkirkland/FTP-Deploy-Action@v4.3.4
    #   with:
    #         local-dir: 'release/'
    #         server: ${{ secrets.FTP_SERVER }}
    #         username: ${{ secrets.FTP_USERNAME }}
    #         password: ${{ secrets.FTP_PASSWORD }}